<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260427131340 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE new_vehicle (warranty INT NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE used_vehicle (mileage INT NOT NULL, general_state VARCHAR(255) NOT NULL, nb_previous_owner INT NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE vehicle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, brand VARCHAR(255) NOT NULL, model VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, energy VARCHAR(255) NOT NULL, gearbox VARCHAR(255) NOT NULL, nb_doors INT NOT NULL, nb_place INT NOT NULL, horses INT NOT NULL, price DOUBLE PRECISION NOT NULL, dtype VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE new_vehicle ADD CONSTRAINT FK_C0C3B768BF396750 FOREIGN KEY (id) REFERENCES vehicle (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE used_vehicle ADD CONSTRAINT FK_9C57C177BF396750 FOREIGN KEY (id) REFERENCES vehicle (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE new_vehicle DROP CONSTRAINT FK_C0C3B768BF396750');
        $this->addSql('ALTER TABLE used_vehicle DROP CONSTRAINT FK_9C57C177BF396750');
        $this->addSql('DROP TABLE new_vehicle');
        $this->addSql('DROP TABLE used_vehicle');
        $this->addSql('DROP TABLE vehicle');
    }
}
